name:                vallance-tracker
version:             0.1.0.0
github:              "alistairbill/vallance-tracker"
license:             BSD3
author:              "Alistair Bill"
maintainer:          "alistair.bill@gmail.com"
copyright:           "2020 Alistair Bill"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alistairbill/vallance-tracker#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- aeson
- postgresql-simple
- req
- resource-pool
- servant-js
- servant-server
- time
- wai
- wai-enforce-https
- warp

library:
  source-dirs: src
  default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings

executables:
  vallance-tracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - vallance-tracker
    - filepath

tests:
  vallance-tracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - vallance-tracker
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
